export abstract class ImageConstant {
  static Facebook = "/icons/Facebook.png"
  static Instagram = "/icons/Instagram.png"
  static Twitter = "/icons/Twitter.png"
  static BANNER1 = "/images/banner1.png"
  static BANNER2 = "/images/banner2.png"
  static BANNER3 = "/images/banner3.jpg"
  static BANNER4 = "/images/banner4.png"
  static Employee = "/images/employee.webp"
  static Privacy = "/images/privacy.webp"
  static SERVICE1 = "/images/service1.webp"
  static SERVICE2 = "/images/service2.webp"
  static SERVICE3 = "/images/service3.webp"
  static SERVICE4 = "/images/service4.webp"
  static SERVICE5 = "/images/service5.webp"
  static SERVICE6 = "/images/service6.webp"
  static SERVICE7 = "/images/service7.jpg"
  static SERVICE8 = "/images/service8.webp"
  static SERVICE9 = "/images/service9.webp"
  static SERVICE10 = "/images/service10.webp"
  static SERVICE11 = "/images/service11.webp"
}